
version: '3.8'

services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
      - "9464:9464"
    networks:
      - app-network

  prometheus:
    image: prom/prometheus:v2.28.1
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - app-network
    depends_on:
      - node-app

  grafana:
    image: grafana/grafana:8.1.2
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana

networks:
  app-network:

volumes:
  grafana_data:
